### ISSUE TITLE
README links broken.

### ISSUE THREAD

**Issue by VictorioBerra** [benallfree/gobot#2]
https://www.npmjs.com/package/gobot

Both of these broken:

![image](https://github.com/benallfree/gobot/assets/2934507/5928ba0a-1f93-4d7c-af35-34806bb05d2c)

**Comment by benallfree** [comment]
Yeah it got out of sync with main.  will be fixed on the next release :)

**Comment by benallfree** [comment]
Thank you for the report!!

Out of curiosity, how are you using gobot?

**Comment by VictorioBerra** [comment]
Just investigating it for now. My goal would be to write a site for PocketBase in JS + the PB JS hooks. I imagine ill be able to have my NPM scripts build my site and launch PB and all that. I really haven't gotten that far yet though.
