### ISSUE TITLE
Updated from alpha 14 to 34 and getting an error

### ISSUE THREAD

**Issue by VictorioBerra** [benallfree/gobot#4]
![image](https://github.com/benallfree/gobot/assets/2934507/99b85f0a-4c72-40cf-bb0b-de7c10a22790)

First it complained with this code:

```js
import { gobot } from "gobot";
const bot = await gobot(`pocketbase`);
bot.run([`--help`]);
```

> Error: pocketbase is not a binary known to Gobot. Try user/repo

this fixed that error:

```js
import { gobot } from "gobot";
const bot = await gobot(`pocketbase/pocketbase`);
bot.run([`--help`]);
```

Got to say, its a major issue that code copied right off the README does not work. Anyway, after fixing the code, it appears pocketbase.exe downloads correctly, but the error says:

> Error: Could not find pocketbase.exe anywhere in path C:\Users\toryb\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.7\x64\win32

Which is imply not true, `ls C:\Users\toryb\AppData\Local\gobot-nodejs\Cache\pocketbase\pocketbase\archives\0.22.7\x64\win32` reveals `pocketbase.exe` is right there in the folder.

**Comment by benallfree** [comment]
Thanks for the report!

I'll have a new release to test soon and could use help testing on Windows. 

Closing because this has already been fixed in the next release.
